### ISSUE TITLE
Is this correct?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/nLTT#22]
I tried to make a simple testcase, as shown [here](http://rpubs.com/richelbilderbeek/244029).

Instead of the expected value of 0.25, I got 0.333. 

@JorikDeBoer: do you think the value should be 0.25 as well?

**Comment by thijsjanzen** [comment]
In general, especially for small phylogenies, the function "nltt_stat_exact" should be preferred. For large phylogenies, "nltt_stat" is approximately correct (very small error), and much faster. However, the approximations used do not perform well for small trees. 

However, for this specific tree, "nltt_stat_exact", throws an error, because there is a polytomy in the phylogeny. In the case of a polytomy, the number of branching times is unequal to the number of lineage changes, which causes trouble.

**Comment by richelbilderbeek** [comment]
Ah, the polytomy is the problem indeed:

```
phylogeny_2 <- ape::read.tree(text = "(((d:0.0000001,c:0.0000001):1,b:1):0.0000001,a:1.0):1;")
```

results in 0.25

Thanks for checking me. You think it is a good idea to check against polytomies? I volunteer to implement it.

**Comment by thijsjanzen** [comment]
yes

**Comment by richelbilderbeek** [comment]
Working on it :+1:

**Comment by richelbilderbeek** [comment]
Fixed in the `develop` branch for now. It would be cool if we'd accept polytomies. But not today :-)

Thanks for checking me!
